name: Check Paclet
on: 
  push: 
    branches:  [main]
  pull_request: 
    branches:  [main]
  workflow_dispatch:
jobs: 
  CheckPaclet: 
    name: Check Paclet
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
    timeout-minutes: 10
    steps: 
    - name: Checkout Code
      id: checkout-code
      uses: actions/checkout@v2
    - name: Check Paclet
      id: check-paclet-step
      uses: rhennigan/check-paclet@v1.4.0